@hotelbooking_HostAddress = http://localhost:5298



###


POST http://localhost:5298/api/customer
Content-Type: application/json

{
    "firstName": "Inge",
    "lastName": "Felsson",
    "email": "unclear@hej.se"
}

###

GET http://localhost:5298/api/customer/12

###

PUT https://localhost:7263/api/customer/1
Content-Type: application/json
{
    "firstName": "sd",
    "lastName": "",
    "email": "per@test.se"
}

###
DELETE https://localhost:7263/api/customer/5

###
PUT https://localhost:7263/api/customer/12
Content-Type: application/json

{
    "firstName": "Ingen",
    "lastName": "Kund",
    "email": "test@test.se"
}

###

GET https://localhost:7263/api/room

###

GET https://localhost:7263/api/room/1

###
POST https://localhost:7263/api/room
Content-Type: application/json
{
    "roomNumber": 203,
    "type": "Double",
    "price": 1275,
    "description": ""
}

###
POST https://localhost:7263/api/room
Content-Type: application/json

{
    "roomNumber": 110,
    "RoomType": "Single",
    "price": 795,
    "description": "heje"
}
###
PUT https://localhost:7263/api/room/1
Content-Type: application/json
{ 
  "roomNumber": 101,
  "RoomType": "Single",
  "price": 775.00,
  "description": ""
}

###

DELETE https://localhost:7263/api/room/8

###

GET https://localhost:7263/api/booking/1

###
POST https://localhost:7263/api/booking
Content-Type: application/json

{
    "customerId": 1,
    "RoomId": 1,
    "checkIn": "2026-09-25",
    "CheckOut": "2026-09-27"
}