@hotelbooking_HostAddress = http://localhost:5298



###


POST http://localhost:5298/api/customer
Content-Type: application/json

{
    "firstName": "hasse",
    "lastName": "larsson",
    "email": "hasse@hej.se"
}

###

GET http://localhost:5298/api/customer/3

###

PUT https://localhost:7263/api/customer/1
Content-Type: application/json
{
    "firstName": "sd",
    "lastName": "",
    "email": "per@test.se"
}

###
DELETE https://localhost:7263/api/customer/3

###
PUT https://localhost:7263/api/customer/12
Content-Type: application/json

{
    "firstName": "Ingen",
    "lastName": "Kund",
    "email": "test@test.se"
}